from PyQt5 import QtCore, QtGui, QtWidgets
#testing git


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 70, 31, 21))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 110, 31, 21))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 150, 31, 21))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 190, 31, 21))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 240, 31, 21))
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 280, 31, 21))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(380, 320, 31, 21))
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(380, 360, 31, 21))
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setObjectName("label_8")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(100, 110, 22, 160))
        self.verticalSlider.setMaximum(400)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(430, 240, 31, 21))
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setText("x")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(430, 70, 31, 21))
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_10.setText("blik")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(430, 190, 31, 21))
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setText("x")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(430, 320, 31, 21))
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setText("x")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(430, 150, 31, 21))
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setText("x")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(430, 110, 31, 21))
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setText("x")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(430, 360, 61, 21))
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setText("x")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(430, 280, 31, 21))
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setText("x")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(40, 300, 111, 51))
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(30, 260, 55, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_19.setObjectName("label_19")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.verticalSlider.valueChanged.connect(self.v_changed)  
    
    def v_changed(self):
        hose=0
        my_value=str(self.verticalSlider.value())
        my_valuei=self.verticalSlider.value()
        self.label_17.setText(my_value)
        if my_valuei <= 80 :
            self.label_10.setText("blik")
        if my_valuei > 80 and my_valuei <= 110 :  
            self.label_10.setText("švici")
            self.label_14.setText("x")
        if my_valuei > 110 and my_valuei <= 150 :  
            self.label_10.setText("x")
            self.label_14.setText("švici")
            self.label_13.setText("x") 
        if my_valuei > 150 and my_valuei <= 190 :  
            self.label_14.setText("x")
            self.label_13.setText("švici")
            self.label_11.setText("x")
        if my_valuei > 190 and my_valuei <= 240 :  
            self.label_13.setText("x")
            self.label_11.setText("švici")
            self.label_9.setText("x")
        if my_valuei > 240 and my_valuei <= 270 :  
            self.label_11.setText("x")
            self.label_9.setText("švici") 
            self.label_16.setText("x")
        if my_valuei > 270 and my_valuei <= 325 :  
            self.label_9.setText("x")
            self.label_16.setText("švici")
            self.label_12.setText("x")
        if my_valuei > 325 and my_valuei <= 370 :  
            self.label_16.setText("x")
            self.label_12.setText("švici")
            self.label_15.setText("x")
        if my_valuei > 370 and my_valuei <= 400 :  
            self.label_12.setText("x")
            self.label_15.setText("Warping")
    
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "0-1"))
        self.label_2.setText(_translate("MainWindow", "1-2"))
        self.label_3.setText(_translate("MainWindow", "2-3"))
        self.label_4.setText(_translate("MainWindow", "3-4"))
        self.label_5.setText(_translate("MainWindow", "4-5"))
        self.label_6.setText(_translate("MainWindow", "5-6"))
        self.label_7.setText(_translate("MainWindow", "6-7"))
        self.label_8.setText(_translate("MainWindow", "7-8"))
        self.label_17.setText(_translate("MainWindow", "Value"))
        self.label_18.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "400"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
